services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: chatting-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/sistem_chatting
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: chatting-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:8
    container_name: sistem-chatting
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
