services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: chatting-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/sistem_chatting
      - CORS_ORIGIN=http://localhost
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatting-frontend
    ports:
      - "3000:80"

  mongo:
    image: mongo:8
    container_name: sistem-chatting
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
